protected/models/Availability.php
<?php

/**
 * This is the model class for table "availability".
 *
 * The followings are the available columns in table 'availability':
 * @property string $id
 * @property string $days
 * @property string $hour_start
 * @property string $hour_end
 * @property string $matter_id
 * @property string $user_id
 *
 * The followings are the available model relations:
 * @property Users $user
 * @property Matters $matter
 * @property Entities $hourStart
 * @property Entities $hourEnd
 */
class Availability extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'availability';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('days', 'required'),
			array('days', 'length', 'max'=>255),
			array('hour_start, hour_end, matter_id, user_id', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, days, hour_start, hour_end, matter_id, user_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'matter' => array(self::BELONGS_TO, 'Matters', 'matter_id'),
			'hourStart' => array(self::BELONGS_TO, 'Entities', 'hour_start'),
			'hourEnd' => array(self::BELONGS_TO, 'Entities', 'hour_end'),
			'day' => array(self::BELONGS_TO, 'Entities', 'days'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'days' => 'Dia',
			'hour_start' => 'Hora Inicio',
			'hour_end' => 'Hora Final',
			'matter_id' => 'Materia',
			'user_id' => 'Usuario',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;
		$criteria->compare('id',$this->id,true);
		$criteria->compare('days',$this->days,true);
		$criteria->compare('hour_start',$this->hour_start,true);
		$criteria->compare('hour_end',$this->hour_end,true);
		$criteria->compare('matter_id',$this->matter_id,true);
		$criteria->compare('user_id',$this->user_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Availability the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function getDays()
    {
        // Consultando Dias de la Semana.
        $days = Entities::model()->findAll('description=:description', array(':description' => 'Days'));
        return CHtml::listData($days,"id","name");
    }


    public function getMenuHours()
    {
        $hours = Entities::model()->findAll('description=:description', array(':description' => 'block'));
        return CHtml::listData($hours,"id","name");
    }
}

protected/controllers/AvailabilityController.php
<?php

class AvailabilityController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','view','admin','create','update','delete','autocomplete','new'),
                'roles'=>array('Admin', 'Coordinador', 'Profesor'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionNew($ide)
	{
		$model=new Availability;
		$model->user_id = $ide;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Availability']))
		{
			$model->attributes=$_POST['Availability'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('new',array(
			'model'=>$model,
		));
	}

	public function actionCreate()
	{
		$model=new Availability;
        $model->user_id = Yii::app()->user->id;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Availability']))
		{
			$model->attributes=$_POST['Availability'];
			$model->matter_id=1;
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Availability']))
		{
			$model->attributes=$_POST['Availability'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Availability');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Availability('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Availability']))
			$model->attributes=$_GET['Availability'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Availability the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Availability::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Availability $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='availability-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

    /* Agregadas */
    public function actionAutocomplete($term)
    {
        $criteria = new CDbCriteria;
        $criteria->compare('LOWER(cod)', strtolower($_GET['term']), true);
        $criteria->order = 'cod';
        $criteria->limit = 30;
        $data = Matters::model()->findAll($criteria);

        if (!empty($data))
        {
            $arr = array();
            foreach ($data as $item) {
                $arr[] = array(
                    'id' => $item->id,
                    'value' => $item->cod.' '.$item->name,
                    'label' => $item->cod.' '.$item->name,
                );
            }
        }
        else
        {
            $arr = array();
            $arr[] = array(
                'id' => '',
                'value' => 'No se han encontrado resultados para su búsqueda',
                'label' => 'No se han encontrado resultados para su búsqueda',
            );
        }

        echo CJSON::encode($arr);
    }
}

protected/views/availability/_form.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'availability-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

    <p class="note"><?php echo Yii::t('app', 'Fields with <span class="required">*</span> are required.') ?></p>

	<?php echo $form->errorSummary($model); ?>

	<div>
        <?php echo $form->dropDownListRow($model,'days',$model->getDays(), array("empty"=>"Seleccione")); ?>
        <?php echo $form->error($model,'days'); ?>
	</div>

	<div>
        <?php echo $form->dropDownListRow($model,'hour_start',$model->getMenuHours(2), array("empty"=>"Seleccione")); ?>
		<?php echo $form->error($model,'hour_start'); ?>
	</div>

	<div>
        <?php echo $form->dropDownListRow($model,'hour_end',$model->getMenuHours(2), array("empty"=>"Seleccione")); ?>
		<?php echo $form->error($model,'hour_end'); ?>
	</div>

	<div>
		<?php echo $form->labelEx($model,'matter_id'); ?>
        <?php
        echo $form->hiddenField($model,'matter_id');
        $this->widget('zii.widgets.jui.CJuiAutoComplete',
            array(
                'name'=>'matter_id_new',
                'model'=>$model,
                'value'=>$model->isNewRecord ? '' : $model->matter_id,
                'source'=>$this->createUrl('availability/autocomplete'),
                'options'=> array(
                    'showAnim'=>'fold',
                    'size'=>'30',
                    'minLength'=>'2',
                    'select'=>"js:function(event, ui) {
										$('#Avalability_matter_id').val(ui.item.id);
									}"
                ),
                'htmlOptions'=> array(
                    'size'=>60,
                    'placeholder'=>'Código de Materia',
                    'title'=>'Indique el Materia.'
                ),
            )
        );

        ?>
		<?php echo $form->error($model,'matter_id'); ?>
	</div>
    <br>
	<div class="buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('class'=>'btn btn-primary btn-large')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/availability/_search.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'days'); ?>
		<?php echo $form->textField($model,'days',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hour_start'); ?>
		<?php echo $form->textField($model,'hour_start'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hour_end'); ?>
		<?php echo $form->textField($model,'hour_end'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'matter_id'); ?>
		<?php echo $form->textField($model,'matter_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/availability/_view.php
<?php
/* @var $this AvailabilityController */
/* @var $data Availability */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('days')); ?>:</b>
	<?php echo CHtml::encode($data->days); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hour_start')); ?>:</b>
	<?php echo CHtml::encode($data->hour_start); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hour_end')); ?>:</b>
	<?php echo CHtml::encode($data->hour_end); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('matter_id')); ?>:</b>
	<?php echo CHtml::encode($data->matter_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />


</div>

protected/views/availability/admin.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */

$this->breadcrumbs=array(
    Yii::t('app','Availabilities')=>array('index'),
    Yii::t('app','Manage'),
);

$this->menu=array(
	array('label'=>Yii::t('app','Create Availability'), 'url'=>array('create')),
);

?>

<h1><?php echo Yii::t('app','Manage Availabilities'); ?></h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'availability-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'days',
		'hour_start',
		'hour_end',
		'matter',
		'user',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/availability/create.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */

$this->breadcrumbs=array(
    Yii::t('app','Availabilities')=>array('index'),
    Yii::t('app','Create'),
);

$this->menu=array(
	array('label'=>Yii::t('app','List Availability'), 'url'=>array('index')),
	array('label'=>Yii::t('app','Manage Availability'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Create Availability'); ?></h1>
    <br>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/availability/index.php
<?php
/* @var $this AvailabilityController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
    Yii::t('app','Availabilities'),
);

$this->menu=array(
	array('label'=>Yii::t('app','Create Availability'), 'url'=>array('create')),
	array('label'=>Yii::t('app','Manage Availability'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Availabilities'); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/availability/update.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */

$this->breadcrumbs=array(
    Yii::t('app','Availabilities')=>array('index'),
	$model->id=>array('view','id'=>$model->id),
    Yii::t('app','Update'),
);

$this->menu=array(
	array('label'=>Yii::t('app','Create Availability'), 'url'=>array('create')),
	array('label'=>Yii::t('app','Manage Availability'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Update Availability').' #'.$model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/availability/view.php
<?php
/* @var $this AvailabilityController */
/* @var $model Availability */

$this->breadcrumbs=array(
	'Availabilities'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>Yii::t('app','Create Availability'), 'url'=>array('create')),
	array('label'=>Yii::t('app','Update Availability'), 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>Yii::t('app','Manage Availability'), 'url'=>array('admin')),
);
?>

<h1>View Availability #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data'=>$model,
	'attributes'=>array(
        array(
            'name'=>'days',
            'value'=>$model->day->name,
        ),
        array(
            'name'=>'hour_start',
            'value'=>$model->hourStart->name,
        ),
        array(
            'name'=>'hour_end',
            'value'=>$model->hourStart->name,
        ),
        array(
            'name'=>'matter_id',
            'value'=>$model->matter->name,
        ),
        array(
            'name'=>'user_id',
            'value'=>$model->user->name,
        ),
	),
)); ?>