protected/models/Matters.php
<?php

/**
 * This is the model class for table "matters".
 *
 * The followings are the available columns in table 'matters':
 * @property string $id
 * @property string $cod
 * @property string $name
 * @property string $priority1
 * @property string $priority2
 * @property integer $unitsCredit
 * @property string $hoursLab
 * @property string $hoursTheory
 * @property string $hoursPractice
 *
 * The followings are the available model relations:
 * @property Semesters[] $semesters
 * @property Semesters[] $semesters1
 * @property Semesters[] $semesters2
 * @property Semesters[] $semesters3
 * @property Semesters[] $semesters4
 * @property Semesters[] $semesters5
 * @property Semesters[] $semesters6
 * @property Semesters[] $semesters7
 * @property Semesters[] $semesters8
 * @property Semesters[] $semesters9
 * @property Availability[] $availabilities
 * @property Users[] $users
 * @property ScheduleDetails[] $scheduleDetails
 * @property ScheduleDetails[] $scheduleDetails1
 * @property ScheduleDetails[] $scheduleDetails2
 * @property ScheduleDetails[] $scheduleDetails3
 * @property ScheduleDetails[] $scheduleDetails4
 * @property ScheduleDetails[] $scheduleDetails5
 * @property ScheduleDetails[] $scheduleDetails6
 * @property ScheduleDetails[] $scheduleDetails7
 * @property ScheduleDetails[] $scheduleDetails8
 * @property ScheduleDetails[] $scheduleDetails9
 * @property ScheduleDetails[] $scheduleDetails10
 * @property ScheduleDetails[] $scheduleDetails11
 * @property ScheduleDetails[] $scheduleDetails12
 */
class Matters extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'matters';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('cod, name, priority1, unitsCredit, hoursTheory', 'required'),
			array('unitsCredit', 'numerical', 'integerOnly'=>true),
			array('cod, name, priority1, priority2, hoursLab, hoursTheory, hoursPractice', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, cod, name, priority1, priority2, unitsCredit, hoursLab, hoursTheory, hoursPractice', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'semesters' => array(self::HAS_MANY, 'Semesters', 'matter'),
			'semesters1' => array(self::HAS_MANY, 'Semesters', 'matter1'),
			'semesters2' => array(self::HAS_MANY, 'Semesters', 'matter2'),
			'semesters3' => array(self::HAS_MANY, 'Semesters', 'matter3'),
			'semesters4' => array(self::HAS_MANY, 'Semesters', 'matter4'),
			'semesters5' => array(self::HAS_MANY, 'Semesters', 'matter5'),
			'semesters6' => array(self::HAS_MANY, 'Semesters', 'matter6'),
			'semesters7' => array(self::HAS_MANY, 'Semesters', 'matter7'),
			'semesters8' => array(self::HAS_MANY, 'Semesters', 'matter8'),
			'semesters9' => array(self::HAS_MANY, 'Semesters', 'matter9'),
			'availabilities' => array(self::HAS_MANY, 'Availability', 'matter_id'),
			'users' => array(self::HAS_MANY, 'Users', 'matter_id'),
			'scheduleDetails' => array(self::HAS_MANY, 'ScheduleDetails', 'block1'),
			'scheduleDetails1' => array(self::HAS_MANY, 'ScheduleDetails', 'block2'),
			'scheduleDetails2' => array(self::HAS_MANY, 'ScheduleDetails', 'block3'),
			'scheduleDetails3' => array(self::HAS_MANY, 'ScheduleDetails', 'block4'),
			'scheduleDetails4' => array(self::HAS_MANY, 'ScheduleDetails', 'block5'),
			'scheduleDetails5' => array(self::HAS_MANY, 'ScheduleDetails', 'block6'),
			'scheduleDetails6' => array(self::HAS_MANY, 'ScheduleDetails', 'block7'),
			'scheduleDetails7' => array(self::HAS_MANY, 'ScheduleDetails', 'block8'),
			'scheduleDetails8' => array(self::HAS_MANY, 'ScheduleDetails', 'block9'),
			'scheduleDetails9' => array(self::HAS_MANY, 'ScheduleDetails', 'block10'),
			'scheduleDetails10' => array(self::HAS_MANY, 'ScheduleDetails', 'block11'),
			'scheduleDetails11' => array(self::HAS_MANY, 'ScheduleDetails', 'block12'),
			'scheduleDetails12' => array(self::HAS_MANY, 'ScheduleDetails', 'block13'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'cod' => 'Código',
            'name' => 'Nombre',
            'priority1' => 'Prelación 1',
            'priority2' => 'Prelación 2',
			'unitsCredit' => 'Unidades de Crédito',
			'hoursLab' => 'Horas Laboratorio',
			'hoursTheory' => 'Horas Teoría',
			'hoursPractice' => 'Horas Práctica',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('cod',$this->cod,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('priority1',$this->priority1,true);
		$criteria->compare('priority2',$this->priority2,true);
		$criteria->compare('unitsCredit',$this->unitsCredit);
		$criteria->compare('hoursLab',$this->hoursLab,true);
		$criteria->compare('hoursTheory',$this->hoursTheory,true);
		$criteria->compare('hoursPractice',$this->hoursPractice,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Matters the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/MattersController.php
<?php

class MattersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','view','admin','create','update','delete','assign','changepass', 'success','autocomplete','aclist'),
                'roles'=>array('Admin', 'Coordinador'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','view','admin','update','changepass', 'success'),
                'roles'=>array('Profesor'),
            ),
            array('allow',
                'actions'=>array('update','changepass', 'success'),
                'roles'=>array('Estudiante'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Matters;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Matters']))
		{
		    //var_dump($_POST['Matters']);
			$model->attributes=$_POST['Matters'];
           // var_dump($model->attributes); die();

            if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Matters']))
		{
			$model->attributes=$_POST['Matters'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Matters');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Matters('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Matters']))
			$model->attributes=$_GET['Matters'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Matters the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Matters::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Matters $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='matters-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}



    /* Agregadas */

    public function action()
    {
        return array(
            'usrlist'=>array(
                'class'=>'application.extensions.EAutoCompleteAction',
                'model'=>'Matter', //Modelo a trabajar
                'attribute'=>'cod', //Campos a mostrar en el textbox
                'id' => 'cod', //Valor a guardar en la base de datos
            ),
        );
    }

    public function actionAutocomplete($term)
    {
        $criteria = new CDbCriteria;
        $criteria->compare('LOWER(cod)', strtolower($_GET['term']), true);
        $criteria->order = 'cod';
        $criteria->limit = 30;
        $data = Matters::model()->findAll($criteria);

        if (!empty($data))
        {
            $arr = array();
            foreach ($data as $item) {
                $arr[] = array(
                    'id' => $item->cod,
                    'value' => $item->cod,
                    'label' => $item->cod .' - '. $item->name,
                );
            }
        }
        else
        {
            $arr = array();
            $arr[] = array(
                'id' => '',
                'value' => 'No se han encontrado resultados para su búsqueda',
                'label' => 'No se han encontrado resultados para su búsqueda',
            );
        }

        echo CJSON::encode($arr);
    }
}

protected/views/matters/_form.php
<?php
/* @var $this MattersController */
/* @var $model Matters */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'matters-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

    <p class="note"><?php echo Yii::t('app','Fields with <span class="required">*</span> are required.'); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<div>
		<?php echo $form->textFieldRow($model,'cod',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'cod'); ?>
	</div>

	<div>
		<?php echo $form->textFieldRow($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div>
        <?php echo $form->labelEx($model,'priority1'); ?>
		<?php echo $form->hiddenField($model,'priority1');
        $this->widget('zii.widgets.jui.CJuiAutoComplete',
            array(
                'name'=>'priority1_new',
                'model'=>$model,
                'value'=>$model->isNewRecord ? '' : $model->cod,
                'source'=>$this->createUrl('matters/autocomplete'), // URL que genera el conjunto de datos
                'options'=> array(
                    'showAnim'=>'fold',
                    'size'=>'30',
                    'minLength'=>'2',
                    'select'=>"js:function(event, ui) {
                                $('#Matters_priority1').val(ui.item.id);
                                }"
                ),
                'htmlOptions'=> array(
                    'size'=>60,
                    'placeholder'=>'Código de Materia - Prelación 1',
                    'title'=>'Indique el Código de Materia.'
                ),
            )
        ); ?>
		<?php echo $form->error($model,'priority1'); ?>
	</div>

	<div>
        <?php echo $form->labelEx($model,'priority2'); ?>
		<?php echo $form->hiddenField($model,'priority2');
        $this->widget('zii.widgets.jui.CJuiAutoComplete',
            array(
                'name'=>'priority2_new',
                'model'=>$model,
                'value'=>$model->isNewRecord ? '' : $model->cod,
                'source'=>$this->createUrl('matters/autocomplete'), // URL que genera el conjunto de datos
                'options'=> array(
                    'showAnim'=>'fold',
                    'size'=>'30',
                    'minLength'=>'2',
                    'select'=>"js:function(event, ui) {
                                $('#Matters_priority2').val(ui.item.id);
                                }"
                ),
                'htmlOptions'=> array(
                    'size'=>60,
                    'placeholder'=>'Código de Materia - Prelación 2',
                    'title'=>'Indique el Código de Materia.'
                ),
            )
        ); ?>
		<?php echo $form->error($model,'priority2'); ?>
	</div>

	<div>
        <?php echo $form->textFieldRow($model,'unitsCredit'); ?>
		<?php echo $form->error($model,'unitsCredit'); ?>
	</div>

	<div>
		<?php echo $form->textFieldRow($model,'hoursLab',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'hoursLab'); ?>
	</div>

	<div>
		<?php echo $form->textFieldRow($model,'hoursTheory',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'hoursTheory'); ?>
	</div>

	<div>
		<?php echo $form->textFieldRow($model,'hoursPractice',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'hoursPractice'); ?>
	</div>

	<div class="buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('class'=>'btn btn-primary btn-lg')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/matters/_search.php
<?php
/* @var $this MattersController */
/* @var $model Matters */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'cod'); ?>
		<?php echo $form->textField($model,'cod',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'priority1'); ?>
		<?php echo $form->textField($model,'priority1',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'priority2'); ?>
		<?php echo $form->textField($model,'priority2',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'unitsCredit'); ?>
		<?php echo $form->textField($model,'unitsCredit'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hoursLab'); ?>
		<?php echo $form->textField($model,'hoursLab',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hoursTheory'); ?>
		<?php echo $form->textField($model,'hoursTheory',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hoursPractice'); ?>
		<?php echo $form->textField($model,'hoursPractice',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/matters/_view.php
<?php
/* @var $this MattersController */
/* @var $data Matters */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('cod')); ?>:</b>
	<?php echo CHtml::encode($data->cod); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('priority1')); ?>:</b>
	<?php echo CHtml::encode($data->priority1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('priority2')); ?>:</b>
	<?php echo CHtml::encode($data->priority2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('unitsCredit')); ?>:</b>
	<?php echo CHtml::encode($data->unitsCredit); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hoursLab')); ?>:</b>
	<?php echo CHtml::encode($data->hoursLab); ?>
	<br />

</div>
<hr>

protected/views/matters/admin.php
<?php
/* @var $this MattersController */
/* @var $model Matters */

$this->breadcrumbs=array(
    Yii::t('app','Matters')=>array('index'),
    Yii::t('app','Manage'),
);

$this->menu=array(
	array('label'=>Yii::t('app','List Matters'), 'url'=>array('index')),
	array('label'=>Yii::t('app','Create Matters'), 'url'=>array('create')),
);

?>

<h1><?php echo Yii::t('app','Manage Matters'); ?></h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'matters-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'cod',
		'name',
		'priority1',
		'priority2',
		'unitsCredit',
		/*
		'hoursLab',
		'hoursTheory',
		'hoursPractice',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/matters/create.php
<?php
/* @var $this MattersController */
/* @var $model Matters */

$this->breadcrumbs=array(
    Yii::t('app','Matters')=>array('index'),
    Yii::t('app','Create'),
);

$this->menu=array(
	array('label'=>Yii::t('app','List Matters'), 'url'=>array('index')),
	array('label'=>Yii::t('app','Manage Matters'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Create Matters'); ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/matters/index.php
<?php
/* @var $this MattersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
    Yii::t('app','Matters'),
);

$this->menu=array(
	array('label'=>Yii::t('app','Create Matters'), 'url'=>array('create')),
	array('label'=>Yii::t('app','Manage Matters'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Matters'); ?></h1>

<?php $this->widget('bootstrap.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/matters/update.php
<?php
/* @var $this MattersController */
/* @var $model Matters */

$this->breadcrumbs=array(
    Yii::t('app','Matters')=>array('index'),
	$model->name=>array('view','id'=>$model->id),
    Yii::t('app','Update'),
);

$this->menu=array(
	array('label'=>Yii::t('app','List Matters'), 'url'=>array('index')),
	array('label'=>Yii::t('app','Create Matters'), 'url'=>array('create')),
	array('label'=>Yii::t('app','View Matters'), 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>Yii::t('app','Manage Matters'), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app','Update Matters').' '.$model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/matters/view.php
<?php
/* @var $this MattersController */
/* @var $model Matters */

$this->breadcrumbs=array(
	'Matters'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Matters', 'url'=>array('index')),
	array('label'=>'Create Matters', 'url'=>array('create')),
	array('label'=>'Update Matters', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Matters', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Matters', 'url'=>array('admin')),
);
?>

<h1>View Matters #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'cod',
		'name',
		'priority1',
		'priority2',
		'unitsCredit',
		'hoursLab',
		'hoursTheory',
		'hoursPractice',
	),
)); ?>